### ISSUE TITLE
[Feature Request] Efficient GCS Bucket Deletion

### ISSUE THREAD

**Issue by justinh-rahb** [RAHB-REALTORS-Association/chat2gpt#69]
🚀 **Feature Request: Efficient GCS Bucket Deletion**

**Description:**  
Enhance the efficiency of file deletions in our GitHub Action, specifically in cases where there are a significant number of files.

**Problem Statement:**  
Currently, our GitHub Action deletes files one by one, which can be time-consuming when there are many files to delete. The goal is to ensure rapid deletions without compromising the integrity of the operation, especially when the file count varies between deployments.

**Proposed Solution:**  
Integrate the `-m` flag into the `gsutil rm` command in our GitHub Action. This will allow for multi-threaded operations and speed up the deletion of multiple files.

```yaml
# Check if the bucket exists and delete it
- name: Delete Existing Bucket
  run: |
    if gsutil ls "gs://$GCS_BUCKET_NAME"; then
      gsutil -m rm -r "gs://$GCS_BUCKET_NAME"
    fi
```

**Benefits:**  
- **Efficiency**: Speeds up the deletion process for multiple files, reducing the overall runtime of the GitHub Action.
- **Scalability**: Even if the number of files increases in the future, the operation will remain efficient.
- **Flexibility**: The `-m` flag is adaptive, meaning it won't have a negative impact if there are fewer files or even none.

**Additional Context:**  
In the current setup, when there are multiple files, the Action suggests using the `-m` flag for efficiency, as evident from the logs.
